[build]
  command = "PRISMA_CLI_BINARY_TARGETS=rhel-openssl-1.0.x npx prisma generate && npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# Next.js plugin for Netlify (App Router supported)
[[plugins]]
  package = "@netlify/plugin-nextjs"
